### PR TITLE
refactor: Get rid of Carthage

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
I'm tired of creating workarounds for all this dependency stuff. Including these helper libs into WDA source would help us to speed up the bootstrapping process. I had to disable "Treat warnings as errors" option, since the added sources are full of warnings, but lets do everything step by step.

### CODE REVIEW

**Comment by KazuCocoa** [comment]
👍 
I'll review and test this pr tomorrow with below envs (as a note):

- Simulators:
    - M1 mac, Xcode 12.2 and 12.3
    - Intel mac, Xcode 10, 11 and 12.
- a real device
    - iOS 14.2 x M1 mac
    - iOS 14.2 x Intel mac (and probably iOS 13 or 12 ipod)

Run build -> check `/source` and video

**Comment by jlipps** [comment]
👍  i can't evaluate the code changes but am a fan of the idea

**Comment by KazuCocoa** [comment]
Everything worked @mykola-mokhnach 
I've tested with:

M1 Mac: Xcode 12.2 and 12.3 (both simulators and a real device)
Intel Mac 10.15.7: Xcode 12.2, 12.3 and Xcode 11 (both simulators and a real device)
Intel Mac 10.14: Xcode 10.3

https://github.com/appium/WebDriverAgent/pull/433 will allow us to build this for over iOS 10

**Review by KazuCocoa — APPROVED** [review]
The change is huge, but I tested various environments. They worked well.
I also reviewed some points like removing carthage stuff from this repository.
This also looks good to me

**Comment by KazuCocoa** [comment]
This will close https://github.com/appium/WebDriverAgent/issues/432

**Comment by choli** [comment]
I might be late to the party, but is there a reason to not use robbiehanson/CocoaAsyncSocket as a Swift pakage? This library seems to be good maintained and swift package manager leaves out the annoying "carthaging", as this obviously was super annoying since xcode 12. Just a question :) thanks

**Comment by KazuCocoa** [comment]
We still support Xcode 10.2+.

I haven't tested well, but if Swift Package manager works well from Xcode 11 and Xcode 12 without the project change, maybe we can use it after supporting only Xcode 11.

I mean once we configure Swift Package manager in Xcode 11.0, the latest Xcode 12.4 (5 beta) also works without modification in project files. (Appium/WDA does not need Carthate, so no strong motivation to use swift package manager for now though)

**Pull request merged**
