### PR TITLE
refactor: Drop workarounds for legacy iOS versions

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
The minimum supported iOS version is now 15, so we do not really care about the older stuff now

### CODE REVIEW

**Comment by KazuCocoa** [comment]
Can we bump the major version as well to make the drop kind of explicit by adding `BREAKING CHANGE:`?
(probably xcuitest driver is also good to bump the major version?)


Removing itself is 👍

**Comment by mykola-mokhnach** [comment]
> Can we bump the major version as well to make the drop kind of explicit by adding `BREAKING CHANGE:`? (probably xcuitest driver is also good to bump the major version?)
> 
> Removing itself is 👍

The change is not breaking because we officially stated way before that xcode 13 is the minimum supported version.

@jlipps what do you think?

**Comment by jlipps** [comment]
Yeah this is a good question. Saying what we support and what we don't doesn't necessarily mean we shouldn't follow semver when enacting our support policies. Saying "we don't support iOS X anymore" is fine, but perhaps we should still release a new major version of the code so that users aren't surprised. If they complain, we point to the policy. In this case I think we should probably release as a breaking change.

**Comment by mykola-mokhnach** [comment]
> Yeah this is a good question. Saying what we support and what we don't doesn't necessarily mean we shouldn't follow semver when enacting our support policies. Saying "we don't support iOS X anymore" is fine, but perhaps we should still release a new major version of the code so that users aren't surprised. If they complain, we point to the policy. In this case I think we should probably release as a breaking change.

Then I would probably have multiple breaking changes. It would make sense to combine them and only bump the major version once

**Comment by jlipps** [comment]
> Then I would probably have multiple breaking changes. It would make sense to combine them and only bump the major version once

yeah makes sense

**Review by KazuCocoa — APPROVED** [review]

**Review by Dan-Maor — APPROVED** [review]

**Pull request merged**
