### PR TITLE
add tapWithNumberOfTaps command

### PR DESCRIPTION
**Pull request by ol-le**
extend command list with multitap command with number of touch points

### CODE REVIEW

**Review by jlipps — APPROVED** [review]

**Comment by ol-le** [comment]
hey @jlipps, @imurchie, could you merge this PR, cause i'm about to open a follow up PR for appium-xcuitest-driver and i'm missing this commit in the submodule

**Comment by morphysk** [comment]
Hey @jlipps Can you please provide ETA when this will be merged as it is already approved? is there anything missing? Thanks

**Comment by jlipps** [comment]
just waiting to see what @imurchie's thoughts are. given that this is a fork of WDA, everything that's merged here creates a maintenance burden when we pull from upstream. but i am for it being merged.

**Comment by morphysk** [comment]
Hey @imurchie can you please comment/approve this PR as it will be great to have this functionality? Thanks

**Review by mykola-mokhnach — COMMENTED** [review]
This functionality will be available as a part of https://github.com/facebook/WebDriverAgent/pull/740

I personally don't see a need in such endpoint

**Pull request closed without merging**
