### PR TITLE
Update Build Config

### PR DESCRIPTION
**Pull request by imurchie**

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
Circle CI still fails on 8.3 and 9.0

**Comment by imurchie** [comment]
These are now failure in the tests, not in the build infrastructure.

**Comment by mykola-mokhnach** [comment]
It looks like CI adds some instability to alerts handling. Try to replace

```objc
- (void)verifyGesture:(NSArray<NSDictionary<NSString *, id> *> *)gesture orientation:(UIDeviceOrientation)orientation
{
  [[XCUIDevice sharedDevice] fb_setDeviceInterfaceOrientation:orientation];
  NSError *error;
  XCTAssertTrue(self.testedApplication.alerts.count == 0);
  XCTAssertTrue([self.testedApplication fb_performAppiumTouchActions:gesture elementCache:nil error:&error]);
  FBAssertWaitTillBecomesTrue(self.testedApplication.alerts.count > 0);
}
```

with 

```objc
- (void)verifyGesture:(NSArray<NSDictionary<NSString *, id> *> *)gesture orientation:(UIDeviceOrientation)orientation
{
  [[XCUIDevice sharedDevice] fb_setDeviceInterfaceOrientation:orientation];
  if (self.testedApplication.alerts.count > 0) {
    [[FBAlert alertWithApplication:self.testedApplication] dismissWithError:nil];
  }
  NSError *error;
  XCTAssertTrue([self.testedApplication fb_performAppiumTouchActions:gesture elementCache:nil error:&error]);
  FBAssertWaitTillBecomesTrue(self.testedApplication.alerts.count > 0);
}
```

**Comment by mykola-mokhnach** [comment]
@imurchie It looks like Circle CI only runs the first part of integration tests rather than running all the parts

**Comment by mykola-mokhnach** [comment]
@imurchie Finally, the tests look much better now and 8.3 is fixed. There is still some instability with alerts here and there, but I assume this happens due to CI slowness. I cannot repro these failures locally on any Xcode version.

**Comment by mykola-mokhnach** [comment]
This PR will be split

**Pull request closed without merging**
