### PR TITLE
Merge with upstream

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
Starting from this point we stop supporting Xcode 8 and lower, since Xcode10 is out

### CODE REVIEW

**Comment by imurchie** [comment]
This seems reasonable. It will need to be held off until 1.9.1 is released, as that ought to have support for Xcode 8 still.

**Comment by mykola-mokhnach** [comment]
If we merge the PR now then it will be present in beta, which is ok

**Comment by imurchie** [comment]
No, if it is in the beta it will be in the release.

**Comment by imurchie** [comment]
It can be merged here and not included in the driver, that is fine. But it means that anything that is merged after won't make it into the driver until after the release, too.

**Pull request merged**
