### PR TITLE
chore: delete Scripts/bootstrap.sh

### PR DESCRIPTION
**Pull request by stefanbirkner**
This script confused me until I found out that it only writes the text
"Dependencies up-to-date" to the console. All the other code is only a
scaffold for code that was removed while removing Carthage in
2ce8571. Therefore I think that this
script is not needed anymore at all.

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
It was a deliberate decision to keep this script in place because depending systems rely on it. Deleting it completely would enforce us to bump the major module version

**Comment by stefanbirkner** [comment]
Another approach would be to delete almost all code in the script. How about that?

**Review by KazuCocoa — APPROVED** [review]

**Comment by mykola-mokhnach** [comment]
I'm ok to bump the major version if you are OK to adjust xcuitest driver module after the major WDA version is bumped @stefanbirkner

**Comment by stefanbirkner** [comment]
https://github.com/appium/appium-xcuitest-driver/pull/1276 is the change in the xcuitest driver module.

**Review by mykola-mokhnach — APPROVED** [review]

**Pull request merged**
