### PR TITLE
chore: Drop obsolete workarounds for coordinates calculation

### PR DESCRIPTION
**Pull request by mykola-mokhnach**

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
I have checked different device orientations and it looks like everything works properly for iOS 16 simulator. @Dan-Maor @KazuCocoa could you also confirm gestures with absolute and relative coordinates work properly on real devices with the recent changes?

**Comment by Dan-Maor** [comment]
I've ran the touch integration tests on real iPhones running 16.5 RC and 15.7.1 and verified landscape taps manually on both as well.
Looks good. I'm a bit preoccupied today so I didn't test swipes manually.

Note that since my Mac is running Ventura I'm unable to verify the behavior with Xcode 13, tested with 14.2.

**Review by Dan-Maor — APPROVED** [review]

**Comment by KazuCocoa** [comment]
let me test tonight

**Comment by KazuCocoa** [comment]
I haven't tested this yet, but hopefully tonight or tomorrow

**Review by KazuCocoa — APPROVED** [review]
Tested alerts and a few actions such as mobile:tap.. It seems good, while I only had iOS 16.5 iPad.. so haven't tested old iOS 15 devices for example.

**Comment by mykola-mokhnach** [comment]
Thank you @KazuCocoa 

I would say we should not care much about iOS 15, - only 10% of all devices still have it according to the stats.

**Pull request merged**
