### PR TITLE
[tvOS]1st: headers

### PR DESCRIPTION
**Pull request by KazuCocoa**
I start working to port https://github.com/facebook/WebDriverAgent/pull/1030

Full diff is https://github.com/appium/WebDriverAgent/compare/master...KazuCocoa:km/tvos?expand=1 . I've separated the PR into 4 sections. To make the change small, I haven't added tests yet (Just tested by manual. Only on simulator, but tested with Xcode 10.1 and 10.2). Will add it after the work.

After the 4 sections, WDA can work for tvOS like below. Then, we can add tvOS support into xcuitest-driver.
tvOS

----

- This PR
    - Almost same as https://github.com/appium/WebDriverAgent/pull/141
        - Headers were handled in the next PR too... I faced many changes than vanilla FB's one in this repo then...
- 2nd PR
    - based on https://github.com/KazuCocoa/WebDriverAgent/pull/3
        - We need to fork https://github.com/KazuCocoa/YYCache to be able to build the lib for tvOS then
            - And add a release tag for Carthage
        - This PR focused on being able to build WDA for tvOS
            - I've created WDARunner_tvOS scheme for tvOS
        - I commented out unnecessary dependencies here to be able to complete building the module. Some methods were broken. They were fixed in the next commit.
- 3rd
    - based on https://github.com/KazuCocoa/WebDriverAgent/pull/4
        - Fixes functionality for tvOS
            - screenshot, interactions
        - Add new feature for tvOS
            - focus, focused attributes
- 4th
    - based on https://github.com/KazuCocoa/WebDriverAgent/pull/5
        - update inspector

After the 4th PR, https://github.com/appium/WebDriverAgent/compare/master...KazuCocoa:km/tvos?expand=1 will be finished. Then, I would like to add tests/Travis build for tvOS build.

You can work WDA on tvOS like below command easily after the above PRs. Screen cast also works.

```
$ curl -X GET http://172.254.99.37:8100/session/376FFB23-A10E-46A7-A594-655A4A98E923/window/size
{
  "value" : {
    "width" : 1920,
    "height" : 1080
  },
  "sessionId" : "376FFB23-A10E-46A7-A594-655A4A98E923",
  "status" : 0
}
$ curl -X GET http://172.254.99.37:8100/session/376FFB23-A10E-46A7-A594-655A4A98E923/element/05000000-0000-0000-067A-000000000000/focused
{
  "value" : false,
  "sessionId" : "376FFB23-A10E-46A7-A594-655A4A98E923",
  "status" : 0
}
$curl -X GET http://172.254.99.37:8100/session/376FFB23-A10E-46A7-A594-655A4A98E923/wda/element/focused
{
  "value" : {
    "ELEMENT" : "6A000000-0000-0000-067A-000000000000"
  },
  "sessionId" : "376FFB23-A10E-46A7-A594-655A4A98E923",
  "status" : 0
}
$ curl -X GET http://172.254.99.37:8100/session/376FFB23-A10E-46A7-A594-655A4A98E923/element/6A000000-0000-0000-067A-000000000000/focused
{
  "value" : true,
  "sessionId" : "376FFB23-A10E-46A7-A594-655A4A98E923",
  "status" : 0
}
```

- http://localhost:8100/inspector
- http://localhost:9100/

Each PR does not break WDARunner scheme.

### CODE REVIEW

**Comment by KazuCocoa** [comment]
cc @imurchie @jlipps @mykola-mokhnach

**Review by mykola-mokhnach — APPROVED** [review]

**Comment by mykola-mokhnach** [comment]
It also makes sense to add a TvOS-based test to Travis, to just make sure it is compilable

**Comment by mykola-mokhnach** [comment]
> We need to fork https://github.com/KazuCocoa/YYCache to be able to build the lib for tvOS then

Do you mind to commit directly into appium/YYCache?

**Comment by KazuCocoa** [comment]
ah, yeah, of course. Will create a commit
> Do you mind to commit directly into appium/YYCache?

**Review by jlipps — APPROVED** [review]
awesome work @KazuCocoa!

**Comment by g-tiwari** [comment]
When can we expect this change to be release in Appium?

**Comment by KazuCocoa** [comment]
Maybe, in 1.13.0

**Comment by g-tiwari** [comment]
That is a great news, waiting for automating tvOS apps via Appium.

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios/ios-tvos.md
@g-tiwari it is available on current appium@beta.
Do you have a physical Apple TV which is not 4k?
If so, could you help us to test it on them?

**Comment by g-tiwari** [comment]
Sure @KazuCocoa , I have the device
I will spend some time testing it

**Pull request merged**
