### PR TITLE
chore: Bump the maximum Xcode version in CI config

### PR DESCRIPTION
**Pull request by mykola-mokhnach**

### CODE REVIEW

**Review by imurchie — APPROVED** [review]
Perhaps an anchor and then aliases would stop having to change so many instances?

**Review by KazuCocoa — APPROVED** [review]

**Comment by imurchie** [comment]
I also don't think 11.4 is available on Travis yet (https://docs.travis-ci.com/user/reference/osx/#xcode-version)

**Comment by mykola-mokhnach** [comment]
yep, we need to wait for Travis to deploy xCode11.4 image

**Comment by mykola-mokhnach** [comment]
closed in favour of https://github.com/appium/WebDriverAgent/pull/301

**Pull request closed without merging**
