### PR TITLE
Bump the recent fixes from FB WDA repository

### PR DESCRIPTION
**Pull request by mykola-mokhnach**

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
Unfortunately some tests are still crashing for this PR: https://travis-ci.org/appium/WebDriverAgent/jobs/470950738#L1888

**Comment by Dan-Maor** [comment]
I'm pretty sure that it's because of the bug I've opened on Facebook's repository after @marekcirkos added the KVO forward mechanism to the FBApplicationProcessProxy class.

While it fixes the shouldWaitForQuiescence issue there is a problem with re-activating apps (initBundleWithPrivatePath fails if there's already an XCUIApplicationProcess for it).

https://github.com/facebook/WebDriverAgent/issues/1044

Edit: Unfortunately it's also making createSession a bit slower (2.5 seconds before, 4.5 seconds after for opening the Settings app).

**Comment by mykola-mokhnach** [comment]
@Dan-Maor Do you have any ideas on how to address it? I cannot merge these fixes in their current state, since it is going to break existing tests for application switching.

**Comment by mykola-mokhnach** [comment]
```
Test Case '-[FBSessionIntegrationTests testMainAppCanBeRestartedInScopeOfTheCurrentSession]' started.
    t =     0.00s Start Test at 2018-12-21 14:25:09.134
2018-12-21 14:25:09.191012+0100 IntegrationTests_1-Runner[74917:1090225] [AXMediaCommon] Unable to look up screen scale
2018-12-21 14:25:09.196431+0100 IntegrationTests_1-Runner[74917:1090225] [AXMediaCommon] Unable to look up screen scale
2018-12-21 14:25:09.196961+0100 IntegrationTests_1-Runner[74917:1090225] [AXMediaCommon] Unexpected physical screen orientation
    t =     0.08s Set Up
    t =     0.12s     Open com.facebook.wda.integrationApp
    t =     0.17s         Launch com.facebook.wda.integrationApp
    t =     4.84s             Wait for com.facebook.wda.integrationApp to idle
    t =     6.39s     Find the "Alerts" Button
    t =     6.40s         Snapshot accessibility hierarchy for app with pid 75011
    t =     6.45s         Find: Descendants matching type Button
    t =     6.45s         Find: Elements matching predicate '"Alerts" IN identifiers'
2018-12-21 14:25:15.581566+0100 IntegrationTests_1-Runner[74917:1090225] Using singleton test manager
    t =     7.50s     Set device orientation to Portrait
    t =     9.09s Terminate com.facebook.wda.integrationApp:75011
    t =    10.18s Open com.facebook.wda.integrationApp
    t =    10.22s     Launch com.facebook.wda.integrationApp
2018-12-21 14:25:19.439879+0100 IntegrationTests_1-Runner[74917:1090225] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Cannot remove an observer <_XCKVOExpectationImplementation 0x6000030d7890> for the key path "currentProcess.applicationState" from <XCUIApplicationImpl 0x6000030da990>, most likely because the value for the key "currentProcess" has changed without an appropriate KVO notification being sent. Check the KVO-compliance of the XCUIApplicationImpl class.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010a6a929b __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000109c45735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010a6a90f5 +[NSException raise:format:] + 197
	3   Foundation                          0x0000000109689a32 -[NSKeyValueNestedProperty object:didRemoveObservance:recurse:] + 659
	4   Foundation                          0x0000000109688c04 -[NSKeyValueUnnestedProperty object:didRemoveObservance:recurse:] + 231
	5   Foundation                          0x00000001096833fb -[NSObject(NSKeyValueObserverRegistration) _removeObserver:forProperty:] + 255
	6   Foundation                          0x000000010968396b -[NSObject(NSKeyValueObserverRegistration) removeObserver:forKeyPath:] + 84
	7   Foundation                          0x000000010968388e -[NSObject(NSKeyValueObserverRegistration) removeObserver:forKeyPath:context:] + 177
	8   XCTest                              0x000000010951f985 __42-[_XCKVOExpectationImplementation cleanup]_block_invoke + 98
	9   libdispatch.dylib                   0x000000010f1e9587 _dispatch_client_callout + 8
	10  libdispatch.dylib                   0x000000010f1f5f87 _dispatch_lane_barrier_sync_invoke_and_complete + 94
	11  XCTest                              0x000000010951f91d -[_XCKVOExpectationImplementation cleanup] + 76
	12  XCTest                              0x000000010951eda3 -[XCTKVOExpectation cleanup] + 48
	13  XCTest                              0x0000000109503b38 -[XCTWaiter _queue_setExpectations:] + 619
	14  libdispatch.dylib                   0x000000010f1e9587 _dispatch_client_callout + 8
	15  libdispatch.dylib                   0x000000010f1f5f87 _dispatch_lane_barrier_sync_invoke_and_complete + 94
	16  XCTest                              0x0000000109502676 -[XCTWaiter waitForExpectations:timeout:enforceOrder:] + 1222
	17  XCTest                              0x000000010950585e +[XCTWaiter waitForExpectations:timeout:enforceOrder:] + 104
	18  XCTest                              0x0000000109526d9f -[XCUIApplicationImpl _waitOnActivationExpectation:] + 138
	19  XCTest                              0x0000000109525525 __42-[XCUIApplicationImpl _launchWithRequest:]_block_invoke + 799
	20  XCTest                              0x0000000109518367 -[XCTContext _runActivityNamed:type:block:] + 245
	21  XCTest                              0x00000001094b932c -[XCTestCase startActivityWithTitle:type:block:] + 218
	22  XCTest                              0x00000001094b9509 -[XCTestCase startActivityWithTitle:block:] + 60
	23  XCTest                              0x00000001095251d0 -[XCUIApplicationImpl _launchWithRequest:] + 216
	24  XCTest                              0x0000000109518367 -[XCTContext _runActivityNamed:type:block:] + 245
	25  XCTest                              0x00000001094b932c -[XCTestCase startActivityWithTitle:type:block:] + 218
	26  XCTest                              0x00000001094b9509 -[XCTestCase startActivityWithTitle:block:] + 60
	27  XCTest                              0x0000000109524d3f -[XCUIApplicationImpl serviceOpenRequest:] + 247
	28  XCTest                              0x00000001094e9d78 -[XCUIApplication _launchUsingXcode:] + 301
	29  WebDriverAgentLib                   0x00000001262abcd3 -[FBApplication launch] + 243
	30  WebDriverAgentLib                   0x0000000126290dcf -[FBSession launchApplicationWithBundleId:shouldWaitForQuiescence:arguments:environment:] + 623
	31  IntegrationTests_1                  0x00000001262103d5 -[FBSessionIntegrationTests testMainAppCanBeRestartedInScopeOfTheCurrentSession] + 2549
	32  CoreFoundation                      0x000000010a6b011c __invoking___ + 140
	33  CoreFoundation                      0x000000010a6ad5b5 -[NSInvocation invoke] + 325
	34  XCTest                              0x00000001094b0b6e __24-[XCTestCase invokeTest]_block_invoke.192 + 78
	35  XCTest                              0x00000001095082e8 -[XCTestCase(Failures) performFailableBlock:testCaseRun:shouldInterruptTest:] + 57
	36  XCTest                              0x0000000109508205 -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] + 96
	37  XCTest                              0x00000001094b082f __24-[XCTestCase invokeTest]_block_invoke + 848
	38  XCTest                              0x000000010950e1ee -[XCUITestContext performInScope:] + 248
	39  XCTest                              0x00000001094b0424 -[XCTestCase testContextPerformInScope:] + 98
	40  XCTest                              0x00000001094b04d2 -[XCTestCase invokeTest] + 137
	41  XCTest                              0x00000001094b200d __26-[XCTestCase performTest:]_block_invoke_2 + 43
	42  XCTest                              0x00000001095082e8 -[XCTestCase(Failures) performFailableBlock:testCaseRun:shouldInterruptTest:] + 57
	43  XCTest                              0x0000000109508205 -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] + 96
	44  XCTest                              0x00000001094b1f24 __26-[XCTestCase performTest:]_block_invoke.326 + 88
	45  XCTest                              0x0000000109518a3b +[XCTContext runInContextForTestCase:block:] + 225
	46  XCTest                              0x00000001094b1653 -[XCTestCase performTest:] + 675
	47  XCTest                              0x00000001094f4802 -[XCTest runTest] + 57
	48  XCTest                              0x00000001094ac85b __27-[XCTestSuite performTest:]_block_invoke + 365
	49  XCTest                              0x00000001094ac033 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 55
	50  XCTest                              0x00000001094ac2f6 -[XCTestSuite performTest:] + 296
	51  XCTest                              0x00000001094f4802 -[XCTest runTest] + 57
	52  XCTest                              0x00000001094ac85b __27-[XCTestSuite performTest:]_block_invoke + 365
	53  XCTest                              0x00000001094ac033 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 55
	54  XCTest                              0x00000001094ac2f6 -[XCTestSuite performTest:] + 296
	55  XCTest                              0x00000001094f4802 -[XCTest runTest] + 57
	56  XCTest                              0x00000001094ac85b __27-[XCTestSuite performTest:]_block_invoke + 365
	57  XCTest                              0x00000001094ac033 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 55
	58  XCTest                              0x00000001094ac2f6 -[XCTestSuite performTest:] + 296
	59  XCTest                              0x00000001094f4802 -[XCTest runTest] + 57
	60  XCTest                              0x0000000109522ea6 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 171
	61  XCTest                              0x0000000109522fc7 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke.80 + 68
	62  XCTest                              0x00000001094c486a -[XCTestObservationCenter _observeTestExecutionForBlock:] + 594
	63  XCTest                              0x0000000109522c1a -[XCTTestRunSession runTestsAndReturnError:] + 623
	64  XCTest                              0x000000010949125a -[XCTestDriver runTestsAndReturnError:] + 422
	65  XCTest                              0x0000000109514fbd _XCTestMain + 1478
	66  IntegrationTests_1-Runner           0x000000010916002d -[_XCTRunnerAppDelegate applicationWillResignActive:] + 0
	67  IntegrationTests_1-Runner           0x000000010915ff2b _XCTRunnerRunTests + 0
	68  CoreFoundation                      0x000000010a60ca3c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	69  CoreFoundation                      0x000000010a60c1f0 __CFRunLoopDoBlocks + 336
	70  CoreFoundation                      0x000000010a606a64 __CFRunLoopRun + 1284
	71  CoreFoundation                      0x000000010a606221 CFRunLoopRunSpecific + 625
	72  GraphicsServices                    0x0000000112d4b1dd GSEventRunModal + 62
	73  UIKitCore                           0x000000010ba7e115 UIApplicationMain + 140
	74  IntegrationTests_1-Runner           0x00000001091601f5 main + 183
	75  libdyld.dylib                       0x000000010f259551 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

```

**Comment by Dan-Maor** [comment]
The KVO changes are really good, but I don't think they can be safely merged at this point.

I started looking into it this week but I'm afraid I don't have any solid directions yet. Looks like something with the KVO forwarding isn't clicking nicely:
* From what I gather, it looks like replacing the XCUIApplicationProcess inside dispatch_async causes initial KVO observers to "go around" the new mechanism (verified by adding logs to the proxied addObserver and removeObserver calls). However, when trying to create a new session when the target app already has a session the proxy mechanism is being used, and causes an exception.
* Removing the dispatch_async from FBApplication causes observers to register through the KVO proxy, however the one of "applicationState" breaks the process when there's an attempt to remove it for some reason.

Perhaps we should revert the KVO PRs until we figure it out.

Unfortunately my Mac is at work so I won't be able to dig into it until next week.

P.S. I had an idea for fixing shouldWaitForQuiescence but @marekcirkos's solution is more generic and I like it more, we just need to figure out what's the missing link here.

**Comment by mykola-mokhnach** [comment]
Thanks for your investigation @Dan-Maor. I see the topic is quite complicated and I possibly cannot help much with that. What I can only say, that the problem that we have is not present for FB WDA, since they don't have application switching implemented. Perhaps, the current way it is done in our fork is not very optimal and needs to be improved. 

Please keep us updated and, again, big thanks to you and @marekcirkos for taking care about such problems.

**Comment by Dan-Maor** [comment]
I made some progress on identifying the issue.

From what I understand, it appears that while we replace XCUIApplicationProcess in the context of XCUIApplicationImpl, XCUIApplicationMonitor still has references to the old XCUIApplicationProcess objects inside internal structures (_launchedApplications, _applicationProcessesForPID and _applicationImplDepot) which link between the XCUIApplicationImpl and its equivalent XCUIApplicationProcess. It can be accessed using "[XCUIApplicationMonitor sharedMonitor]".

Violently purging the sharedMonitor and its depot using KVC allows creating another session with a previously launched application, however I'd rather find a more gentle way of modifying the internal dictionaries and change the references to our newly created FBApplicationProcessProxy, if that's possible (pretty sure it is). I'm not certain about other effects of the violent approach.

Might take me a while to continue with it since I'm working on other urgent tasks at the moment (I've analyzed it while waiting for a rare exception on another issue I'm working on), so if the changes are urgent I suggest to perhaps merge all but the last two commits since these are the ones in need of attention.

**Comment by mykola-mokhnach** [comment]
@Dan-Maor We could easily wait, there is no rush. We'd rather merge a correct fix, which does not fail any tests.

**Comment by marekcirkos** [comment]
@Dan-Maor I think the problem is that dispatch_async is executed in next runloop run, but check probably takes place in the same call stack later (however proxy is already nested). We can either delay nesting proxy, but then we will miss some calls to it, or take completely different approach and replace proxy and modify `XCUIApplicationProcess` methods at runtime.
I really wanted to avoid that, but it might be our next best move.

**Comment by mykola-mokhnach** [comment]
@Dan-Maor Do you by any chance have time to work on this fix. BTW, have you seen 
https://github.com/facebook/WebDriverAgent/issues/1076? It looks like everything will stop working again soon.

**Comment by Dan-Maor** [comment]
Not anytime soon I’m afraid, I’m extremely overloaded at the moment.

About Xcode 10.2 - from what I can tell the sharedClient has been removed in favor of a property of XCUIDevice (accessibilityClient), hopefully just using it instead will give the same behavior. This is also the case for the sharedMonitor from XCUIApplicationMonitor, by the way.

**Comment by mykola-mokhnach** [comment]
Thanks for the hint @Dan-Maor 
I'll try to provide a fix for that

**Comment by Dan-Maor** [comment]
After looking into it a bit more I tend to agree with @marekcirkos - I could't find a way for still using the FBApplicationProcessProxy with the KVO changes while maintaining the ability to re-activate applications. Looks like we'll have to resort to overriding some methods on runtime (I'm working on it).

By the way - there's an issue currently in master where setting waitForQuiescence to false doesn't make a difference with Xcode 9.4 and above due to not registering for an observer in FBApplication if applicationProcessTracker exists (it has been added in 9.4, not 10.2).

**Comment by coinhu1995** [comment]
@Dan-Maor still facing this issue. The environment:

Xcode 11.2.1
iOS 12.1.2

> 2019-12-05 12:46:36.332030+0700 WebDriverAgentRunner-Runner[1530:118687] Starting screenshots broadcast to 127.0.0.1:63335

> 2019-12-05 12:46:36.386360+0700 WebDriverAgentRunner-Runner[1530:119043] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Cannot remove an observer <NSKeyValueObservance 0x282401da0> for the key path "currentProcess.applicationState" from <XCUIApplicationImpl 0x2809af6b0>, most likely because the value for the key "currentProcess" has changed without an appropriate KVO notification being sent. Check the KVO-compliance of the XCUIApplicationImpl class.'

> *** First throw call stack:
> (0x1c8fa1ea4 0x1c8171a50 0x1c8ea8484 0x1c9996410 0x1c996f1c4 0x1c996ef78 0x1c996edf8 0x1c999627c 0x1c996f1c4 0x1c996ef78 0x1c996edf8 0x1c996eb38 0x1013927ec 0x1c89da484 0x1c89875c8 0x10139276c 0x101391c0c 0x101372c6c 0x1c89da484 0x1c89875c8 0x1013717d4 0x101374804 0x101330208 0x101358c28 0x101358548 0x1012fdd04 0x1024b7fc8 0x1024b25e4 0x1024ada78 0x1024b2044 0x1024b1944 0x10247c3c4 0x10247c088 0x10247bae0 0x1c89da484 0x1c897d82c 0x1c898db9c 0x1c8981a9c 0x1c8982718 0x1c898aeb8 0x1c8bbd0dc 0x1c8bbfcec)

> libc++abi.dylib: terminating with uncaught exception of type NSException

>

**Comment by Dan-Maor** [comment]
Are you setting shouldWaitForQuiescence to false?
If not - that's a different issue.
Also - does it happen at a certain point or randomly?

**Comment by coinhu1995** [comment]
@Dan-Maor

> Are you setting shouldWaitForQuiescence to false?

Yes, it is "NO" from WDA.
`static BOOL FBShouldWaitForQuiescence = NO;`

> Also - does it happen at a certain point or randomly?

it is randomly

**Comment by Dan-Maor** [comment]
Are you setting it explicitly to false? appium-xcuitest-driver sends it as 'true' by default unless the capability is manually set to false.
`let shouldWaitForQuiescence = util.hasValue(this.opts.waitForQuiescence) ? this.opts.waitForQuiescence : true;`

**Comment by coinhu1995** [comment]
@Dan-Maor
I just run WDA from xcodebuild command (Not run with appium).  

Also i changed 
`
requirements = FBParseCapabilities((NSDictionary *)request.arguments[@"capabilities"]
[FBConfiguration setShouldWaitForQuiescence:[requirements[@"shouldWaitForQuiescence"] boolValue]];`
to 
`[FBConfiguration setShouldWaitForQuiescence:NO];`

in FBSessionCommand.m but it did not work

**Comment by Dan-Maor** [comment]
* If you want to disable the mechanism you should set the value to YES, like it is being received from Appium by default.
* I've noticed that you're mirroring the screen, does it happen when the screen is not being mirrored?
* Please completely reset the project, and try to reproduce the issue.
* If the issue still happens - try to _create a session_ with `shouldWaitForQuiescence` capability set to true and check whether the issue still happens.

If the issue doesn't happen when the capability is set to true, please open an issue in the main Appium repo with all of the details.
* Complete scenario, including which app is in the front when the issue happens.
* A gist with a full syslog of the session of the occurrence.
* Nice to have - since you're running it manually, please run it with Xcode directly and attach a screenshot of the stacktrace.

**Comment by coinhu1995** [comment]
I ran it with Xcode and set shouldWaitForQuiescence to TRUE and also FALSE. After WDA start successfully (ServerURLHere->http://172.27.168.30:8100<-ServerURLHere). I open localhost:9100, the error occurred.
I am running Xocde 11.2.1 and using XCTAutomationSupport.framework, XCTest.framework from Xcode 10.1. Does it affect to this issue ?

**Comment by Dan-Maor** [comment]
If setting shouldWaitForQuiescence to true doesn't make a difference then it's not the same issue as before.

Opening localhost:9100 is what triggers the video stream to start, so it may be related, however mix and matching like that is never a good idea and may well be the cause of the issue.

We can't really help with this sort of setup since it is not intended to run this way.

**Pull request closed without merging**
