### PR TITLE
refactor: Remove obsolete coordinate calculation workarounds needed for older xCode SDKs

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
Apple did actually fix most of the orientation issues that XCTest was suffering of before. Which means we do not need to keep ugly hacks anymore since we only support Xcode 13+

### CODE REVIEW

**Comment by KazuCocoa** [comment]
Let me test with a few real devices, iPhone and iPad

**Comment by KazuCocoa** [comment]
Not fully checked yet, but an element screenshot in landscape mode in iPad 16's element section had the correct area by this removal. <- done
e.g.

Current master:
Screen Shot 2023-05-13 at 2 24 29

This PR:
Screen Shot 2023-05-13 at 2 31 25


Will check (I'll update this list):


iPad mini 16.5, iPhone 16

- element screenshot (random)
    - landscape
    - portrait
- alert element
    - click action
        - permission alert
    - element selection
        - A few Apple's official apps
- scroll, tap (w3c actions base)
    - Maps app, Safari's scroll, and "Freeform" official app to paint something
    - Rarely XCTest itself did not respond for a while, but it worked eventually. Most cases worked fine. It seems like staber than previously (long ago) I tested

(feel free to add items if you have any concerns)

**Review by KazuCocoa — APPROVED** [review]
In my testing, I confirmed this removal fixed an iPad's issue, such as an element screenshot. Scroll./picker wheel action also it seems like pretty stable than previously I tested (long before tho).

This PR itself seems good to me

**Comment by mykola-mokhnach** [comment]
> In my testing, I confirmed this removal fixed an iPad's issue, such as an element screenshot. Scroll./picker wheel action also it seems like pretty stable than previously I tested (long before tho).
> 
> This PR itself seems good to me

Thanks for checking it @KazuCocoa

**Pull request merged**
