### PR TITLE
feat: Make isFocused attribute available for iOS elements

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
https://github.com/appium/appium/issues/18600

### CODE REVIEW

**Review by KazuCocoa — APPROVED** [review]
lg

minor: Will you include for xpath as well?
https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Utilities/FBXPath.m#L98-L104

**Comment by KazuCocoa** [comment]
Btw, I think we also can expose isSelected and hasKeyboardFocus for the page source and attribute. let me create this idea

**Comment by mykola-mokhnach** [comment]
> lg
> 
> minor: Will you include for xpath as well? https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Utilities/FBXPath.m#L98-L104

not sure we need to overload page source xml with this stuff
this attribute makes sense for a very limited set of elements

**Comment by KazuCocoa** [comment]
Sounds good. not have a strong motivation for the XPath things.

(not for this pr)
Btw, what I could remember about this focus in non tvOS env, I could not find cases the return value became true in the past. Probably.... bluetooth keyboard or something accessibility functionality is needed for ios...? (i don't know well)

I wondered if the original motivation to expose the focused was expected by hasKeyboardFocus's result. I mean if an element was focused by keyboard like a search bar.

**Comment by KazuCocoa** [comment]
btw, should we merge this for https://github.com/appium/appium-xcuitest-driver/pull/1661 ...? let me merge this

**Pull request merged**
