### PR TITLE
build: make sure we do not get rate-limited getting deps

### PR DESCRIPTION
**Pull request by imurchie**

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
What is the purpose of this change?

**Review by jlipps — APPROVED** [review]
THANKS I have been bitten by this while running workshops before

**Comment by imurchie** [comment]
Periodic errors of the sort
```
414.95s$ ./Scripts/build.sh
+./Scripts/bootstrap.sh -d
Fetching dependencies
*** Checking out RoutingHTTPServer at "v1.2.1"
*** Checking out CocoaAsyncSocket at "7.6.3"
*** Checking out YYCache at "1.1.0"
*** Cloning RoutingHTTPServer
*** Cloning CocoaAsyncSocket
*** Cloning YYCache
*** xcodebuild output can be found in /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/carthage-xcodebuild.hA5Dby.log
*** Skipped downloading CocoaAsyncSocket.framework binary due to the error:
	"Maximum number of login attempts exceeded. Please try again later."
*** Skipped downloading RoutingHTTPServer.framework binary due to the error:
	"Maximum number of login attempts exceeded. Please try again later."
*** Skipped downloading YYCache.framework binary due to the error:
	"Maximum number of login attempts exceeded. Please try again later."
*** Building scheme "tvOS Framework" in CocoaAsyncSocket.xcodeproj
*** Building scheme "iOS Framework" in CocoaAsyncSocket.xcodeproj
*** Building scheme "RoutingHTTPServer tvOS" in RoutingHTTPServer.xcodeproj
*** Building scheme "RoutingHTTPServer iOS" in RoutingHTTPServer.xcodeproj
*** Building scheme "YYCache iOS" in YYCache.xcodeproj
*** Building scheme "YYCache tvOS" in YYCache.xcodeproj
```

https://travis-ci.org/appium/WebDriverAgent/jobs/614004476#L1916-L1937
https://travis-ci.org/appium/WebDriverAgent/jobs/604124575#L1916-L1937
https://travis-ci.org/appium/WebDriverAgent/jobs/604124571#L1916-L1937

**Comment by mykola-mokhnach** [comment]
Isn't carthage smart enough to download sources if such errors happens?

**Comment by imurchie** [comment]
No. Carthage is spectacularly stupid, actually.

**Review by mykola-mokhnach — APPROVED** [review]
I'm sad about carthage :(

Do you know if anybody already reported such improvement into their issues repository?

**Review by KazuCocoa — APPROVED** [review]

**Pull request merged**
