### PR TITLE
feat: Add a new endpoint for element rotation

### PR DESCRIPTION
**Pull request by mykola-mokhnach**

### CODE REVIEW

**Review by KazuCocoa — APPROVED** [review]
looks good 👍 Will we add a mobile command to call this?

**Comment by mykola-mokhnach** [comment]
> Will we add a mobile command to call this?

Yep, as soon as new WDA version is released

**Comment by KazuCocoa** [comment]
👍

**Comment by jlipps** [comment]
XCUITest lets you rotate elements? that's kind of wacky?

**Pull request merged**
