### PR TITLE
feat: Make it possible to use custom caching strategy for all element locators

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
The PR adds the new "useNativeCachingStrategy" capability. Being set to `false` it enforces all cached elements to be resolved using their UUIDs rather than actual query attributes. This makes the following element lookups more "stable".

Related to https://discuss.appium.io/t/elements-state-coming-from-xpath-vs-ios-predicate-string/34016

### CODE REVIEW

**Review by KazuCocoa — APPROVED** [review]
interesting...

**Review by Dan-Maor — APPROVED** [review]

**Comment by igorgiumellizup** [comment]
False is the default value? Won't that change the default caching behavior of native locators, since they resolve elements by queries?

**Comment by mykola-mokhnach** [comment]
The default value is to keep the current behaviour (true). In order to set the custom one `useNativeCachingStrategy` must be explicitly set to `false`

**Comment by mykola-mokhnach** [comment]
@igorgiumellizup Does the current implementation work for you?

**Comment by igorgiumellizup** [comment]
> @igorgiumellizup Does the current implementation work for you?

I haven't been able to test it yet. When I have time, how can I import it in my gradle project? I'm using it like this
`compile group: 'io.appium', name: 'java-client', version: '7.4.1'`

**Comment by mykola-mokhnach** [comment]
This is the server change. It has nothing to do with java client. You could use `npm link` with that branch similarly to https://github.com/appium/appium/issues/14693#issuecomment-684878582 in order to link the changed module into your server deployment. Then it would probably make sense to hardcode a the corresponding capability and set it to NO at https://github.com/appium/WebDriverAgent/pull/516/files#diff-7debbf48ac1513ec716fc7d72a09c224118ac2d4835e8f3d0517d457ee39c9acR159 as the parent module does not have it defined yet

**Comment by igorgiumellizup** [comment]
I couldn't validade the changes due to technical problemas with my PC. I'd appreciate if someone could do this task. Just use the example described in the related Appium forum. Thanks

**Pull request merged**
