### PR TITLE
Consider containers as visible by default

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
Assume containers are visible if they have intersection with the current window

### CODE REVIEW

**Review by jlipps — APPROVED** [review]
👍  makes sense

**Review by imurchie — APPROVED** [review]

**Comment by mykola-mokhnach** [comment]
@imurchie I've slightly changed the algorithm to make it more flexible. Can you please try once more?

**Comment by mykola-mokhnach** [comment]
Hi @imurchie . I've merged the changed from https://github.com/appium/WebDriverAgent/pull/29 to this PR. Can you please check it locally for the last time before it is merged? Everything works for me locally. Thanks in advance

**Review by imurchie — APPROVED** [review]
Looking like it's working! Thanks!

**Comment by mykola-mokhnach** [comment]
Thanks you for your help @imurchie

**Pull request merged**
