### PR TITLE
Add support of multiple apps in scope of a single session

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
Xcode9 introduced support for multiple applications running in scope of a single XCTest session. This PR adds several new endpoints in order to make this functionality available from WDA.

### CODE REVIEW

**Review by imurchie — APPROVED** [review]
Does this still work with Xcode 8.3/iOS 9.3?

**Comment by mykola-mokhnach** [comment]
this only works since XcodeSDK 9 on Simulator (iOS version does not matter) and since iOS11 on real devices if WDA has been built on Xcode9+

**Comment by mykola-mokhnach** [comment]
I'll describe this in a separate document after it's merged

**Comment by imurchie** [comment]
I understand the _feature_ is new. Does the system work as it did on Xcode 8.3?

**Comment by mykola-mokhnach** [comment]
yes, nothing is changed for older clients. They will just get an exception if they try to use the newly added endpoints from this PR. Everything else stays the same.

**Comment by imurchie** [comment]
Cool. Thanks.

**Pull request merged**
