### PR TITLE
make devices filtering script compatible with python3

### PR DESCRIPTION
**Pull request by joshuasince1986**
in Python3, len(filter(...)) doesn't work because filter returns iterator instead of a list. Using list comprehension to fix this python3 compatibility issue.

### CODE REVIEW

**Comment by KazuCocoa** [comment]
Thanks!

Could you sign for the CLA?

- after
> $ xcrun simctl list -j devices | python2.7 -c "import sys,json;print(' '.join(map(lambda x: x[0], filter(lambda x: len([y for y in x[1] if y.get('availability') == '(available)']) > 0, json.load(sys.stdin)['devices'].items()))))"
com.apple.CoreSimulator.SimRuntime.tvOS-12-1 com.apple.CoreSimulator.SimRuntime.iOS-11-4 com.apple.CoreSimulator.SimRuntime.iOS-12-0 com.apple.CoreSimulator.SimRuntime.iOS-12-1 com.apple.CoreSimulator.SimRuntime.iOS-10-3 com.apple.CoreSimulator.SimRuntime.watchOS-5-1 com.apple.CoreSimulator.SimRuntime.iOS-9-3

> $ xcrun simctl list -j devices | python3 -c "import sys,json;print(' '.join(map(lambda x: x[0], filter(lambda x: len([y for y in x[1] if y.get('availability') == '(available)']) > 0, json.load(sys.stdin)['devices'].items()))))"
com.apple.CoreSimulator.SimRuntime.iOS-10-3 com.apple.CoreSimulator.SimRuntime.iOS-11-4 com.apple.CoreSimulator.SimRuntime.iOS-12-1 com.apple.CoreSimulator.SimRuntime.iOS-12-0 com.apple.CoreSimulator.SimRuntime.watchOS-5-1 com.apple.CoreSimulator.SimRuntime.tvOS-12-1 com.apple.CoreSimulator.SimRuntime.iOS-9-3

- before
> $ xcrun simctl list -j devices | python2.7 -c "import sys,json;print(' '.join(map(lambda x: x[0], filter(lambda x: len(filter(lambda y: y.get('availability') == '(available)', x[1])) > 0, json.load(sys.stdin)['devices'].items()))))"
com.apple.CoreSimulator.SimRuntime.tvOS-12-1 com.apple.CoreSimulator.SimRuntime.iOS-11-4 com.apple.CoreSimulator.SimRuntime.iOS-12-0 com.apple.CoreSimulator.SimRuntime.iOS-12-1 com.apple.CoreSimulator.SimRuntime.iOS-10-3 com.apple.CoreSimulator.SimRuntime.watchOS-5-1 com.apple.CoreSimulator.SimRuntime.iOS-9-3

> $ xcrun simctl list -j devices | python3 -c "import sys,json;print(' '.join(map(lambda x: x[0], filter(lambda x: len(filter(lambda y: y.get('availability') == '(available)', x[1])) > 0, json.load(sys.stdin)['devices'].items()))))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
TypeError: object of type 'filter' has no len()

cc @dpgraham

**Review by KazuCocoa — APPROVED** [review]

**Comment by joshuasince1986** [comment]
@KazuCocoa , cla already signed with primary email address of my account  but another "FullName" instead of "joshuasince1986 ". how to make clabot do recheck?

**Comment by KazuCocoa** [comment]
@joshuasince1986 
Maybe, you signed with an email which was different from an email you used to commit  https://github.com/appium/WebDriverAgent/pull/168/commits/4f7131fbe3ad37726b2f9512a004354e267662f3 . Then, I think you can follow either below way:

1. sign with the email you used to commit the change
2. rebase the commit with your primary email

Could you take a look again?

**Review by mykola-mokhnach — APPROVED** [review]

**Comment by joshuasince1986** [comment]
@KazuCocoa , cla signed , pending for CI tests complete

**Pull request merged**
