### PR TITLE
Scrap the inspector

### PR DESCRIPTION
**Pull request by imurchie**
Yank out the Inspector, which we do not recommend using, and have no intention of maintaining support for.

### CODE REVIEW

**Review by umutuzgur — APPROVED** [review]
Double Approval just because I love code deletion

**Review by jlipps — APPROVED** [review]
`+2 -1,552` 😻

**Review by mykola-mokhnach — APPROVED** [review]
👍

**Comment by jineshqa** [comment]
Wish you would not have scrapped it :-(. It was super useful in working hybrid apps and easily identify the app bundle id for push notification and things like that. Any chance you would consider putting it back?

**Comment by jlipps** [comment]
@jineshqa can you raise feature requests for appium desktop instead? if the WDA inspector could do it, then theoretically Appium Desktop can do it just as easily, and now that we are fully maintaining WDA, we do not want to maintain two different kinds of inspectors.

**Pull request merged**
