### PR TITLE
add tapWithNumberOfTaps command

### PR DESCRIPTION
**Pull request by ol-le**
extend command list with multitap command with number of touch points

### CODE REVIEW

**Review by imurchie — APPROVED** [review]
Looks good to me! Thank you!

**Comment by imurchie** [comment]
@ol-le Can you sign the CLA? We cannot merge this without it. :(

**Comment by ol-le** [comment]
hey, i have signed it but for some reason i still get the message about missing CLA

**Comment by ol-le** [comment]
wrong email in commit, i will close this PR and open a new one
sorry for inconvenience

**Pull request closed without merging**
