### PR TITLE
Make screenshots quality and the framerate dynamically configurable

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
The same stuff as @qmfrederik did in https://github.com/appium/WebDriverAgent/pull/124, but severely improved

### CODE REVIEW

**Comment by qmfrederik** [comment]
Thanks! I find it a bit odd that the configuration for the MJPEG server, which runs a port 9100, is done over the settings of the WebDriver, which runs at port 8100, but I understand the reasoning and this works for me. I'll close the other PR.

**Comment by mykola-mokhnach** [comment]
@KazuCocoa can you please check this PR?

**Review by KazuCocoa — APPROVED** [review]
The code looks 👍 
I'll do dynamic test applying this change in my local later (maybe, today or tomorrow)

**Comment by mykola-mokhnach** [comment]
Great. Please let me know how it worked, so I can merge the PR

**Comment by KazuCocoa** [comment]
Workrd well after applying below in xcuitest-driver ✅ 

```diff
$ git diff
diff --git a/WebDriverAgent b/WebDriverAgent
index cd64224..dea0ca8 160000
--- a/WebDriverAgent
+++ b/WebDriverAgent
@@ -1 +1 @@
-Subproject commit cd642244aab7ec544141e85ed84d9ad6acd05e90
+Subproject commit dea0ca8b823d6d8ac424ec8071df04488d367e93
diff --git a/lib/driver.js b/lib/driver.js
index fefbc24..e84cfbf 100644
--- a/lib/driver.js
+++ b/lib/driver.js
@@ -143,7 +143,9 @@ class XCUITestDriver extends BaseDriver {
   async onSettingsUpdate (key, value) {
     const proxySettings = [
       'shouldUseCompactResponses',
-      'elementResponseAttributes'
+      'elementResponseAttributes',
+      'mjpegServerScreenshotQuality',
+      'mjpegServerFramerate'
     ];
     if (key === 'nativeWebTap') {
       this.opts.nativeWebTap = !!value;
```

- variation
```ruby
        @@driver.update_settings({ mjpegServerScreenshotQuality: 10, mjpegServerFramerate: 1})
        @@driver.update_settings({ mjpegServerScreenshotQuality: 0, mjpegServerFramerate: -100})
        @@driver.update_settings({ mjpegServerScreenshotQuality: -10, mjpegServerFramerate: 60})
        @@driver.update_settings({ mjpegServerScreenshotQuality: 100, mjpegServerFramerate: 60})
```

**Pull request merged**
