### PR TITLE
MJPEG server: control framerate, quality via environment variables

### PR DESCRIPTION
**Pull request by qmfrederik**
The framerate and quality of the MJPEG server are currently hardcoded at 10 FPS and a quality of 25.

Different use cases may have different requirements; so this PR allows you to change these parameters via environment variables.

As a special case, you can set the framerate to 0, giving you the highest framerate the device can deliver.

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
I'd rather make these dynamic settings, so we could change them while the session is running

**Comment by mykola-mokhnach** [comment]
Nit: Check `handleGetSettings` and `handleSetSettings` handlers

**Comment by qmfrederik** [comment]
@mykola-mokhnach Thanks for the feedback. I'll have a look at the proposed changes. The current approach "works for me", so it may take a bit of time.

Do you prefer to keep the PR open or do you want me to close it and re-open when I find the time to adapt it?

**Comment by mykola-mokhnach** [comment]
> Do you prefer to keep the PR open or do you want me to close it and re-open when I find the time to adapt it?

Do what is more convenient for you

**Comment by qmfrederik** [comment]
Closing in favor of #125

**Pull request closed without merging**
