### PR TITLE
chore: Bump fastlane version

### PR DESCRIPTION
**Pull request by mykola-mokhnach**

### CODE REVIEW

**Review by KazuCocoa — APPROVED** [review]

**Comment by mykola-mokhnach** [comment]
It seems like the recent Fastlane version has issues while working with Xcode10. Reported it as https://github.com/fastlane/fastlane/issues/15686

**Comment by KazuCocoa** [comment]
Nice 🍏CI status 🎉

**Comment by mykola-mokhnach** [comment]
Yep, I've [confirmed](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/issues/174#issuecomment-557773953) the fix
Now, waiting for it to be published.

All kudos to @lyndsey-ferguson

**Comment by lyndsey-ferguson** [comment]
Thanks!

**Comment by lyndsey-ferguson** [comment]
`multi_scan` is fixed in [v3.8.15](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/releases/tag/v3.8.15)

**Pull request merged**
